###LOCAL HOST###

###Home
GET http://localhost:8080/

###Get book list
GET http://localhost:8080/book

###Get book by id
GET http://localhost:8080/book/671b9817e5e845f90e475083

###Create book
POST http://localhost:8080/book HTTP/1.1
Content-Type: application/json

{
  "title": "The Winds of Winter",
  "author": "George R.R. Martin",
  "genre": "Fantasy",
  "year": 2023,
  "pages": 900,
  "language": "English",
  "price": 50000
}

###Edit book
PUT http://localhost:8080/book/671d000eca07172818d509e2 HTTP/1.1
Content-Type: application/json

{
  "title": "The Winds of Winter",
  "author": "George R.R. Martin",
  "genre": "Fantasy",
  "year": 2023,
  "pages": 900,
  "language": "English",
  "price": 99999
}

###Delete book
DELETE http://localhost:8080/book/671d000eca07172818d509e2

###Get book by author
GET http://localhost:8080/book/find-by-author/George R.R. Martin

###Get book by genre
GET http://localhost:8080/book/find-by-genre/Fantasy




###Get author
GET http://localhost:8080/author

###Get author by id
GET http://localhost:8080/author/671c601a78fadd47df20166d

###Create author
POST http://localhost:8080/author HTTP/1.1
Content-Type: application/json

{
  "name": "George R.R. Martin",
  "birthday": "1948-09-20"
}

###Edit user
PUT http://localhost:8080/author/671d01f6ca07172818d509e3 HTTP/1.1
Content-Type: application/json

{
  "name": "George R.R. Martin",
  "birthday": "1948-11-11"
}

###Delete user
DELETE http://localhost:8080/author/671d01f6ca07172818d509e3


# Production

###Home
GET https://cse341final-mxdo.onrender.com/

### Login
GET https://cse341final-mxdo.onrender.com/login/

###Get book list
GET https://cse341final-mxdo.onrender.com/book

###Get book by id
GET https://cse341final-mxdo.onrender.com/book/671b9817e5e845f90e475083

###Create book
POST https://cse341final-mxdo.onrender.com/book HTTP/1.1
Content-Type: application/json

{
  "title": "The Winds of Winter",
  "author": "George R.R. Martin",
  "genre": "Fantasy",
  "year": 2023,
  "pages": 900,
  "language": "English",
  "price": 50000
}

###Edit book
PUT https://cse341final-mxdo.onrender.com/book/671d000eca07172818d509e2 HTTP/1.1
Content-Type: application/json

{
  "title": "The Winds of Winter",
  "author": "George R.R. Martin",
  "genre": "Fantasy",
  "year": 2023,
  "pages": 900,
  "language": "English",
  "price": 99999
}

###Delete book
DELETE https://cse341final-mxdo.onrender.com/book/671d000eca07172818d509e2

###Get book by author
GET https://cse341final-mxdo.onrender.com/book/find-by-author/George R.R. Martin

###Get book by genre
GET https://cse341final-mxdo.onrender.com/book/find-by-genre/Fantasy




###Get author
GET https://cse341final-mxdo.onrender.com/author

###Get author by id
GET https://cse341final-mxdo.onrender.com/author/671c601a78fadd47df20166d

###Create author
POST https://cse341final-mxdo.onrender.com/author HTTP/1.1
Content-Type: application/json

{
  "name": "George R.R. Martin",
  "birthday": "1948-09-20"
}

###Edit author
PUT https://cse341final-mxdo.onrender.com/author/671d01f6ca07172818d509e3 HTTP/1.1
Content-Type: application/json

{
  "name": "George R.R. Martin",
  "birthday": "1948-11-11"
}

###Delete author
DELETE https://cse341final-mxdo.onrender.com/author/671d01f6ca07172818d509e3



### Get user
GET https://cse341final-mxdo.onrender.com/user

### Get user by ID
GET https://cse341final-mxdo.onrender.com/user/671c639078fadd47df201673

### Create user
POST https://cse341final-mxdo.onrender.com/user/ HTTP/1.1
Content-Type: application/json

{
  "firstname": "Atsushi",
  "lastname": "Karino",
  "username": "ak715",
  "password": "A1ice_Pass!"
}

### Edit user
PUT https://cse341final-mxdo.onrender.com/user/ID HTTP/1.1
Content-Type: application/json

{
  "firstname": "Atsushi",
  "lastname": "Karino",
  "username": "ak715",
  "password": "Password!!!"
}

### Delete user 
DELETE https://cse341final-mxdo.onrender.com/user/ID



### Get Reviews
GET https://cse341final-mxdo.onrender.com/review/


### Get review by ID
GET https://cse341final-mxdo.onrender.com/review/671c67f478fadd47df201678

### Get review by book
GET https://cse341final-mxdo.onrender.com/review/find-by-book/671b9817e5e845f90e475083

### Get review by username
GET https://cse341final-mxdo.onrender.com/review/find-by-user/blue_sky23

### Create review
POST https://cse341final-mxdo.onrender.com/review/ HTTP/1.1
Content-Type: application/json

{
  "bookID": "671b9817e5e845f90e475083",
  "username": "blue_sky23",
  "review": 5,
  "comment": "An unforgettable story with deep characters.",
  "date": "2023-10-01"
}

### Edit review
PUT https://cse341final-mxdo.onrender.com/review/ID HTTP/1.1
Content-Type: application/json

{
  "bookID": "671b9817e5e845f90e475083",
  "username": "blue_sky23",
  "review": 5,
  "comment": "An unforgettable story with deep characters.",
  "date": "2023-11-11"
}

### Delete review
DELETE https://cse341final-mxdo.onrender.com/review/ID